#!/usr/bin/python
# coding: UTF-8
#
# Copyright (C) 2015 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

from SOAPpy import WSDL
import argparse
import ConfigParser

parser = argparse.ArgumentParser(description='Opens Mantis issues')

parser.add_argument('--summary',     help='Issue summary', required=True)
parser.add_argument('--description', help='Issue description', required=True)
parser.add_argument('--project-id',  help='Project ID', required=True)
parser.add_argument('--handler-id',  help='Handler ID')
parser.add_argument('--handler-name',  help='Handler name')
parser.add_argument('--reporter-id',  help='Reporter ID')
parser.add_argument('--reporter-name',  help='Reporter name')
parser.add_argument('--status-id',  help='Status ID')
parser.add_argument('--configuration-file',
    help='INI file containing Mantis parameters',
    default='/etc/mantis.ini'
)

args = parser.parse_args()

# Read parameters from configuration file
config = ConfigParser.RawConfigParser()
config.read(args.configuration_file)

wsdl     = config.get('Mantis', 'wsdl')
username = config.get('Mantis', 'username')
password = config.get('Mantis', 'password')

issue = {
    'summary': args.summary,
    'description': args.description,
    'project':
    {
        'id': args.project_id,
    },
}

# Define issue 'handler id' if needed
if 'handler_id' in args:
	issue['handler'] = {'id': args.handler_id };

# Define issue 'handler name' if needed
if 'handler_name' in args:
	issue['handler'] = {'name': args.handler_name };

# define issue 'status id' if needed
if 'status_id' in args:
	issue['status'] = {'id': args.status_id };

# define issue 'reporter id' if needed
if 'reporter_id' in args:
	issue['reporter'] = {'id': args.reporter_id };

# define issue 'reporter name' if needed
if 'reporter_name' in args:
	issue['reporter'] = {'name': args.reporter_name };

mantis = WSDL.Proxy(wsdl)

mantis.mc_issue_add(username, password, issue)
